name: Pull Request Build

on:
  pull_request:
    branches: ["main"]
    types: [opened, edited, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js from package.json
        uses: actions/setup-node@v3
        with:
          node-version-file: "package.json"

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Checkout PokeAPI repo
        uses: actions/checkout@v4
        with:
          repository: "PokeAPI/pokeapi"
          path: pokeapi
          token: ${{ github.token }}

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
          cache: "pip"
          cache-dependency-path: pokeapi/requirements.txt

      - name: Build sqlite3 database
        run: |
          cd pokeapi

          pip install -r requirements.txt
          python manage.py migrate --settings=config.local

          cd ..

          cp pokeapi/db.sqlite3 public/pokemon.db

      - name: Build Routes
        run: pnpm routes

      - name: Generate database types
        run: pnpm db:types

      - name: Lint application
        run: pnpm lint

      - name: Check formatting
        run: pnpm format:check

      - name: Build application
        run: pnpm build

      - name: Test application
        run: pnpm test

      - name: Validate PR title with commitlint
        uses: kevintyj/prlint@v1

      - uses: hmarr/auto-approve-action@v3
        with:
          review-message: "Build completed, auto approving PR"
